### ISSUE TITLE
Gibberish appears on the flight-strip

### ISSUE THREAD

**Issue by JasonMKurtz** [openscope/openscope#152]
It doesn't happen all the time, but occasionally the flight-strips get unreadable when issuing a new route. 

<img width="251" alt="screen shot 2017-01-21 at 6 24 53 pm" src="https://cloud.githubusercontent.com/assets/2831185/22178580/7b425440-e008-11e6-81d9-c73b2c215f23.png">

**Comment by n8rzz** [comment]
this was, specifically on `EDDH`, right?

**Comment by JasonMKurtz** [comment]
I'm also pretty sure I saw it happen at EBBR. Those are the airports I've spent the most time playing.

**Comment by erikquinn** [comment]
Many places.

**Comment by n8rzz** [comment]
for this we either round the altitude value in the `AircraftStringView` or we floor it when we do calculations.  

I'm not sure where and when this crept in, but I'd be curious to find out the why here.  It wasn't always this way.

**Comment by n8rzz** [comment]
the cause of this issue seems to be stemming from `Waypoint.ensureValidContentsForAircraft()`
```javascript
    ensureValidContentsForAircraft(aircraft) {
        this.altitude = _defaultTo(this.altitude, aircraft.altitude);
        this.speed = _defaultTo(this.speed, aircraft.speed);
        this.heading = _defaultTo(this.heading, aircraft.heading);

        return this;
    }
```

**Comment by n8rzz** [comment]
added bandaid with [n8rzz#272](https://github.com/n8rzz/atc/issues/272)

**Comment by erikquinn** [comment]
> added bandaid with n8rzz#272

@n8rzz So.. this is resolved, no?

**Comment by n8rzz** [comment]
@erikquinn yes, but not correctly.  

a bandaid was applied via n8rzz#272 which fixes the glitch, but that does not solve the issue.  openscope/openscope#168 was added for removing the bandaid, which should happen once this issue has been properly fixed.

**Comment by erikquinn** [comment]
Understood. The problem is no longer *apparent*, so this issue can be considered resolved, even though further work will be needed to get the proper fix put in place. Closing!
