### ISSUE TITLE
WIP airports not loading

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#675]
Many work-in-progress airports do not have any defined entries or exits. This will cause some serious issues in the fms, and a new throw was recently added to prevent this from being possible. As a result, a ton of WIP airports are not able to run at all. Those that can be fixed must be fixed, and all others deactivated in the load list.

**Comment by sam-irl** [comment]
Affected airports:
EBBR
EDDF
EDDH
EDDT
EGKK
EGLC
EGLL
EGNM
EKCH
ENGM
GCRR
KLAS
KPDX
KPHX
LOWW
OMDB
VHHH

**Comment by erikquinn** [comment]
Resolved by #676. Closing.

**Comment by pushkarlaulkar** [comment]
Hello, the above-mentioned airports are still not loading in google chrome neither in firefox..

**Comment by indianbhaji** [comment]
@pushkarlaulkar Hello, WIP airports are not enabled by default - you need to enable them by clicking the settings icon (last icon on the bottom bar) then enable WIP airports by changing the option from no to yes

**Comment by erikquinn** [comment]
Turned out to be that recent changes now _require_ video maps, which many WIP airports do not have. This is addressed in #832 (bugfix #831) .
